### ISSUE TITLE
Research react native

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#10]
Everyone must research react native and how to use it. In the team discord there are resources to get everyone started

**Comment by MarkoSchuetz** [comment]
As an issue that does not work very well: when is this done? Who can close this and why?

**Comment by gabrielpadilla7** [comment]
> As an issue that does not work very well: when is this done? Who can close this and why?

I will close this issue as this is an issue that will be worked on throughout the semester, as all of the students that are in the team must learn how to use react native (if they have not used it beforehand).
