### ISSUE TITLE
Sign Up/Login Screen (frontend)

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#103]
# Description
Crear una pagina de sign up tal que el usuario pueda ingresar su información como:
- Nombre
- Edad
- Fecha de nacimiento
- Email
- Password

Si esta en la pagina de Login, el usuario solamente necesita ingresar esta informacion:

- Email
- Password

*por el momento estos son los parametros que tenemos. De haber más ponerlos en este issue para dialogarlo en el equipo y ver si se aprueba.

**Comment by gabrielpadilla7** [comment]
Updated parameters

**Comment by JuanQ1226** [comment]
Saludos , any updates? Se que está apretada la cosa con thanksgiving pero espero que se pueda terminar.

**Comment by JorgeC08** [comment]
Saludos Juan, yo acabo de salir de dos exámenes y dos proyectos. Voy a ver si brego hoy con esto.
________________________________

**Comment by JuanQ1226** [comment]
Pide ayuda que para eso estamos en equipo.

**Comment by juan-ortiz92** [comment]
Perdon que no me puesto en contacto. He estado trabajando mucho en una asignacion de Programming Languages. Ya pronto voy a trabajar en mi parte con el Milestone 3.
________________________________

**Comment by JuanQ1226** [comment]
Ok comuníquense con los de backend que ellos están haciendo las cosas de una forma específica. En el aspecto de las variables y todo eso.

**Comment by JorgeC08** [comment]
Saludos, ya tengo mas o menos el Login y Signup screen pero me esta fallando en que cuando entre me envié al RoadMap. También falta hacer la conexión con el Backend. Por ahora tengo que acepte cualquier Login para probarlo

**Comment by JuanQ1226** [comment]
Para conectarlo al backend communicate con los de backend y traten de hacerlo juntos para que no haya problemas.

**Comment by JorgeC08** [comment]
Ya encontré el problema, voy a subirlo a un nuevo branch llamado signup-login-screen. Lo que falta es conectarlo con el backend, maybe decirle a los que bregan con el UI para que se vea bonito y también si se puede poner algo para corroborar que es un email porque hasta el momento no se tiene ninguna corroboración.

**Comment by JuanQ1226** [comment]
Bien. Lo del email es una buena preocupación si da tiempo se hace después. Vamos a concentrarnos en que funcione primero.

**Comment by JuanQ1226** [comment]
Lo del ui vamos a ver si nos da tiempo también
