### ISSUE TITLE
Create list of exercises

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#104]
# Description
Crear una lista de ejercicios donde la misma se ingrese en la base de datos como ejercicios "pre-hechos".
Por el momento, los ejercicios deben de ser aquellos que requieran un cronometro para así aplicar el timer que se tiene.

La lista requiere que tenga:

- El nombre de ejercicio
- Descripcion de ejercicio
- Tiempo sugerido
- Categoria (muscle group)
- XP  (avg 10)

**Comment by gabrielpadilla7** [comment]
Updated para reflejar lo que la lista requiere que tenga.

**Comment by edgarsuarez123** [comment]
type Exercise = {
  name: string;
  description: string;
  muscleGroup: string;
  duration: string;
  xp: number;
};

const exercises: Exercise[] = [
  {
    name: "Push-up",
    description: "A classic bodyweight exercise that strengthens the chest and triceps.",
    muscleGroup: "Chest, Shoulders, Triceps",
    duration: "60000 ms",
    Xp: 10,
  },
  {
    name: "Squats",
    description: "A lower body exercise that targets the quadriceps and glutes.",
    muscleGroup: "Quadriceps, Glutes",
    duration: "60000 ms",
    xp: 13,
  },
  {
    name: "Plank",
    description: "An isometric core exercise that strengthens the abdominal muscles.",
    muscleGroup: "Core",
    duration: "60000 ms",
    xp: 12,
  },
  {
    name: "Bicep Curls",
    description: "An exercise that targets the biceps and helps build arm strength.",
    muscleGroup: "Biceps",
    duration: "60000 ms",
    xp: 11,
  },
  {
    name: "Lunges",
    description: "A lower body exercise that works the quadriceps, hamstrings, and glutes.",
    muscleGroup: "Quadriceps, Hamstrings, Glutes",
    duration: "60000 ms",
    xp: 13,
  },
  {
    name: "Sit-ups",
    description: "An abdominal exercise that targets the rectus abdominis.",
    muscleGroup: "Abdominals",
    duration: "60000 ms",
    xp: 10,
  },
  {
    name: "Burpees",
    description: "A full-body exercise that combines squats, push-ups, and jumps.",
    muscleGroup: "Full Body",
    duration: "60000 ms",
    xp: 15,
  },
  {
    name: "Pull-ups",
    description: "An upper body exercise that targets the back and biceps.",
    muscleGroup: "Back, Biceps",
    duration: "60000 ms",
    xp: 15,
  },
  {
    name: "Deadlifts",
    description: "A compound exercise that works the lower back, hamstrings, and glutes.",
    muscleGroup: "Lower Back, Hamstrings, Glutes",
    duration: "60000 ms",
    xp: 20,
  },
  {
    name: "Mountain Climbers",
    description: "A dynamic core exercise that also engages the shoulders and legs.",
    muscleGroup: "Core, Shoulders, Legs",
    duration: "60000 ms",
    xp: 10,
  },
  {
    name: "Tricep Dips",
    description: "An exercise that targets the triceps and helps tone the arms.",
    muscleGroup: "Triceps",
    duration: "60000 ms",
    xp: 13,
  },
  {
    name: "Russian Twists",
    description: "A core exercise that involves twisting your torso to work the obliques.",
    muscleGroup: "Obliques",
    duration: "60000 ms",
    xp: 12,
  },
  {
    name: "Leg Raises",
    description: "An abdominal exercise that targets the lower abs.",
    muscleGroup: "Lower Abs",
    duration: "60000 ms",
    xp: 11,
  },
  {
    name: "Calf Raises",
    description: "An exercise that strengthens the calf muscles.",
    muscleGroup: "Calves",
    duration: "60000 ms",
    xp: 10,
  },
  {
    name: "Box Jumps",
    description: "A plyometric exercise that enhances leg power and explosiveness.",
    muscleGroup: "Legs",
    duration: "60000 ms",
    xp: 13,
  },
  {
    name: "Kettlebell Swings",
    description: "A full-body exercise that combines cardio and strength training.",
    muscleGroup: "Full Body",
    duration: "60000 ms",
    xp: 12,
  },
  {
    name: "High Knees",
    description: "A cardiovascular exercise that engages the core and legs.",
    muscleGroup: "Core, Legs",
    duration: "60000 ms",
    xp: 5,
  },
  {
    name: "Wall Sits",
    description: "A lower body exercise that builds endurance in the legs.",
    muscleGroup: "Legs",
    duration: "60000 ms",
    xp: 7,
  },
  {
    name: "Push-up to T-Plank",
    description: "A challenging exercise that combines push-ups and side planks.",
    muscleGroup: "Chest, Triceps, Core",
    duration: "60000 ms",
    xp: 10,
  },
  {
    name: "Rowing Machine",
    description: "A cardio exercise that also engages the back and arms.",
    muscleGroup: "Back, Arms",
    duration: "60000 ms",
    xp: 7,
  },
  {
    name: "Leg Press",
    description: "A resistance machine exercise that targets the legs.",
    muscleGroup: "Legs",
    duration: "60000 ms",
    xp: 12,
  },
  {
    name: "Dumbbell Bench Press",
    description: "An upper body exercise that works the chest and triceps with dumbbells.",
    muscleGroup: "Chest, Triceps",
    duration: "60000 ms",
    xp: 15,
  },
  {
    name: "Hamstring Curls",
    description: "An isolation exercise that focuses on the hamstrings.",
    muscleGroup: "Hamstrings",
    duration: "60000 ms",
    xp: 12,
  },
  {
    name: "Shoulder Press",
    description: "An exercise that targets the shoulder muscles and deltoids.",
    muscleGroup: "Shoulders",
    duration: "60000 ms",
    xp: 12,},

**Comment by warm007** [comment]
{
    name: "Seated Leg Extensions",
    description: "A machine exercise that isolates the quadriceps.",
    muscleGroup: "Quadriceps",
    duration: "60000 ms",
    xp: 12,
  },
  {
    name: "Bent-over Rows",
    description: "An exercise that targets the back and helps improve posture.",
    muscleGroup: "Back",
    duration: "60000 ms",
    xp: 15,
  },
  {
    name: "Crunches",
    description: "An abdominal exercise that strengthens the core.",
    muscleGroup: "Core",
    duration: "60000 ms",
    xp: 8,
  },
  {
    name: "Jumping Jacks",
    description: "A cardio exercise that engages the whole body and improves cardiovascular fitness.",
    muscleGroup: "Full Body",
    duration: "60000 ms",
    xp: 5,
  },
  {
    name: "Inverted Rows",
    description: "An exercise that targets the upper back and biceps.",
    muscleGroup: "Upper Back, Biceps",
    duration: "60000 ms",
    xp: 15,
  },
   {
    name: "Side Planks",
    description: "An isometric core exercise that focuses on the obliques.",
    muscleGroup: "Obliques",
    duration: "60000 ms",
    xp: 6,
  },
  {
    name: "Jump Rope",
    description: "A cardiovascular exercise that enhances coordination and endurance.",
    muscleGroup: "Full Body",
    duration: "60000 ms",
    xp: 5,
  },
  {
    name: "Bent-over Dumbbell Rows",
    description: "An exercise that works the upper back, biceps, and helps improve posture.",
    muscleGroup: "Upper Back, Biceps",
    duration: "60000 ms",
    xp: 9,
  },
  {
    name: "Lateral Raises",
    description: "An exercise that targets the shoulder muscles and deltoids.",
    muscleGroup: "Shoulders",
    duration: "60000 ms",
    xp: 10,
  },
  {
    name: "Knee-to-Elbow Planks",
    description: "A core exercise that engages the obliques by bringing the knees to the elbows.",
    muscleGroup: "Obliques, Core",
    duration: "60000 ms",
    xp: 15,
  },
   {
    name: "Romanian Deadlifts",
    description: "An exercise that works the lower back, hamstrings, and glutes with a focus on hamstring development.",
    muscleGroup: "Lower Back, Hamstrings, Glutes",
    duration: "60000 ms",
    xp: 15,
  },
  {
    name: "Hanging Leg Raises",
    description: "An advanced abdominal exercise that targets the lower abs and requires a pull-up bar.",
    muscleGroup: "Lower Abs",
    duration: "60000 ms",
    xp: 15,
  },
  {
    name: "Skater Hops",
    description: "A plyometric exercise that enhances lateral leg strength and agility.",
    muscleGroup: "Legs",
    duration: "60000 ms",
    xp: 5,
  },
  {
    name: "Battle Ropes",
    description: "A full-body cardiovascular exercise that also engages the shoulders and arms.",
    muscleGroup: "Full Body, Shoulders, Arms",
    duration: "60000 ms",
    xp: 20,
  },
  {
    name: "Russian Push-ups",
    description: "A challenging variation of push-ups that combines push-up and rotation.",
    muscleGroup: "Chest, Triceps, Core",
    duration: "60000 ms",
    xp: 20,
  },
  {
    name: "Boxing Punches",
    description: "A cardio exercise that involves various punching combinations for a full-body workout.",
    muscleGroup: "Full Body",
    duration: "60000 ms",
    xp: 15,
  },
  {
    name: "Dumbbell Shrugs",
    description: "An exercise that targets the trapezius muscles in the upper back and neck.",
    muscleGroup: "Trapezius",
    duration: "60000 ms",
    xp: 12,
  },
  {
    name: "Step-ups",
    description: "A lower body exercise that targets the quadriceps, hamstrings, and glutes.",
    muscleGroup: "Quadriceps, Hamstrings, Glutes",
    duration: "60000 ms",
    xp: 10,
  },
  {
    name: "Dumbbell Bicep Curls",
    description: "An exercise that targets the biceps with dumbbells for arm strength.",
    muscleGroup: "Biceps",
    duration: "60000 ms",
    xp: 10,
  },
  {
    name: "Side Leg Raises",
    description: "A leg exercise that targets the outer thigh muscles.",
    muscleGroup: "Legs",
    duration: "60000 ms",
    xp: 20,
  },
  {
    name: "Dumbbell Flyes",
    description: "An exercise that isolates the chest muscles and enhances pectoral development.",
    muscleGroup: "Chest",
    duration: "60000 ms",
    xp: 15,
  },

**Comment by gabrielpadilla7** [comment]
A long list of exercises were provided. Closing issue
