### ISSUE TITLE
Finish the Release

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#106]
# Description
Juntar **todos los branches a beta** para así aprovar el beta y sacar el release en el main.
Los branches que ya se hicieron merge pueden ser borrados. Asegurense de que manejen bien los merge conflicts en caso de haber.

**Comment by gabrielpadilla7** [comment]
Merged todos los branches a beta, NO BORRAR BRANCHES
