### ISSUE TITLE
Sign up/Login Screen (backend)

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#107]
Referencing #103 

Make the necessary connections from the front end to the back end. 

The following information is required to be added to the database:

- Name
- Email
- Password
- Date of Birth

The following information will be initialized, but the user will NOT input anything for it 

- id (randomly generated)
- Time exercised (init to 0)
- Exercise count (how many exercises done, init to 0)

**Comment by JuanQ1226** [comment]
Any updates on this ? Se que está apretada la cosa con thanksgiving pero espero que se pueda terminar.

**Comment by GregAlexander07** [comment]
Handler may take a little more than I anticipated, anyways @Chosen-Juan1 ill keep in touch contigo hoy

**Comment by GregAlexander07** [comment]
Le pregunte y me dijo que iba a bregar con eso el viernes. Si acaso yo lo ayudo implementando el approute y el que sabe mas del code de front end pues lo ayudo con lo que mecesite

**Comment by JuanQ1226** [comment]
Perfecto. Falto un detalle que era mostrarle al usuario el time spent y exercise count en el profile page que voy a crear otro Task. Debería hacerse por uno de ustedes ya que se tiene que saber cómo hacer el fetch. Pero si quieren que ponga otra persona está bien.

**Comment by Chosen-Juan1** [comment]
Ya el code en si esta hecho, tengo que probarlo para ver si funciona (I have never used typescript pero creo que lo que tengo should work)

**Comment by Chosen-Juan1** [comment]
> Perfecto. Falto un detalle que era mostrarle al usuario el time spent y exercise count en el profile page que voy a crear otro Task. Debería hacerse por uno de ustedes ya que se tiene que saber cómo hacer el fetch. Pero si quieren que ponga otra persona está bien.

I think I can do that, sería un fecha request adicional. That said, como va front end con el login? Porque yo estoy probando el código con variables hechas acá, pero me imagino que el programa va a usar user input.

**Comment by Chosen-Juan1** [comment]
Si lo tienen hecho, puedo darle pull y cambiar el comportamiento del fetch para que use el input.

**Comment by JuanQ1226** [comment]
Acabe de pregúntales te avisaré.

**Comment by GregAlexander07** [comment]
Update: ya implemente el api para que meneje crear usuarios 
Le hice commit al branch de frontend-to-backend 

Problem: its not stable, hay un problema de importas que python no brega conmigo, pero la logica ya está
Si alguien le quiere echar un vistas. Seguiria dandole cabeza pero voy a bajar a mi pueblo ahora, lo puedo seguir cuando llegue

@Chosen-Juan1 hice un comment para cuando reciba el json el user_handler, te sale como se tiene que ver

**Comment by JuanQ1226** [comment]
Miren hablé con los de frontend y van a empezar ahora. Es tarde pero lo bueno es se puede comunicar con ellos para que hagan el form de la forma que funcione con lo que tienen
