### ISSUE TITLE
Application of topics - Agile [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#113]
# Description

Verificar lo que ya está en la documentación y añadir/mejorar lo que se propone en este issue.
Al finalizar marcar como done este task y el issue de referencia [issue #111]

## Agile
```
The team shows how they use sprints to structure the project, use a
product backlog and sprint backlogs, maintain the backlogs
feature-oriented, and do sprint review and planning.
```

- [x] Done ✅

**Comment by AlfredoSoto1** [comment]
El en issue #111 aparece la rubrica para que se dejen llevar

**Comment by AlfredoSoto1** [comment]
Recuerden, todo lo viejo que se modifique tiene que estar diferenciado a lo nuevo que se añada. Esto puede ser con distintos highliters en el documento.

**Comment by AlfredoSoto1** [comment]
Recalco una vez más para que no se cometa el mismo error. Recuerden que lo nuevo debe de estar highlighted de un color **DISTINTO** a lo que se valla a modificar del documento (lo del milestone 1). Eso fue unas de las criticas que el profe dejó.

**Comment by AlfredoSoto1** [comment]
Aquí les dejo la rúbrica de referencia para que comparen si lo que añadieron/modificaron es cumple con lo que el profesor reclama.

![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/108200951/c13761f2-9191-4d2b-a8ab-32d307ee270e)

**Comment by warm007** [comment]
Agile Methodology Adoption for Fitness Project:

To ensure the successful execution of this fitness project, we are adopting the Agile methodology. Agile's adaptability and responsiveness to changing needs and preferences will guide our development process, breaking the project into smaller, manageable segments or sprints.
Function Segments
1.	Roadmap for Goal-Oriented Progression:
•	Description: The project features a gamified progression system with predefined workouts, serving as a roadmap for users.
•	Purpose: Guides users through sequential workouts, unlocking progressively to simulate a gaming-like progression.
•	Benefits: Users experience a sense of accomplishment, akin to leveling up in a game, fostering motivation and adherence.
•	Implementation: A quick-play option is available, and workouts unlock sequentially based on user progress, encouraging users to complete one to unlock the next.
2.	Customizable Workouts:
•	Description: Users have the flexibility to create their own workouts, selecting exercises from a library or designing entirely new ones.
•	Purpose: Provides a high level of customization, allowing users to tailor their fitness experience to individual needs and preferences.
•	Benefits: Users can adapt their fitness routine as their goals evolve, ensuring a unique and dynamic journey.
•	Implementation: The platform offers access to preselected workouts, and users can design entirely new exercises using a user-friendly interface.
3.	Exercise and Workout Management:
•	Description: Users can save selected exercises and entire workout routines, creating a personal library for easy access and reuse.
•	Purpose: Enhances user customization and convenience, enabling efficient organization of their fitness resources.
•	Benefits: Streamlines the fitness journey, making it more organized and user-friendly, ultimately saving users time in planning and execution.
•	Implementation: The platform includes a feature that allows users to save, organize, and reuse their preferred exercises and workout routines.
4.	Achievement System:
•	Description: The project will implement an achievement system, rewarding users for consistency and exercise quantity.
•	Purpose: Motivates users to maintain exercise routines by providing tangible rewards, such as badges and other recognitions.
•	Benefits: Enhances the overall gamified fitness experience, creating a sense of accomplishment and encouraging users to stay engaged and committed.
•	Implementation: Users earn badges and rewards based on achieving fitness milestones, fostering a positive feedback loop.
5.	Engaging User Interface:
•	Description: The platform's user interface is designed to be intuitive and engaging, resembling an interactive gaming experience.
•	Purpose: Enhances user motivation and enjoyment during exercise sessions through a visually appealing and user-friendly interface.
•	Benefits: Features like progress bars and XP tracking provide users with real-time feedback on their fitness journey, creating an immersive and enjoyable experience.
•	Implementation: The user interface incorporates gamified elements, progress tracking tools such as progress bars, and XP indicators to create an immersive and visually appealing fitness environment.

**Comment by warm007** [comment]
Buenas tardes, @AlfredoSoto1 @gabrielpadilla7! Adjunto, la documentación del Agile Topic.  Si alguno la puede revisar y me dejan saber para añadirla al Google Docs.

**Comment by JorgeC08** [comment]
> Buenas tardes, @AlfredoSoto1 @gabrielpadilla7! Adjunto, la documentación del Agile Topic. Si alguno la puede revisar y me dejan saber para añadirla al Google Docs.

Saludos William. Todo parece estar super, lo único que se podría añadir es en el 'Description' en el segundo punto, esto:

"or selecting one of the pre-made challenges."

Lo cual quedaria como: 

"Description: Users have the flexibility to create their own workouts, selecting exercises from a library, designing entirely new ones or selecting one of the pre-made challenges." 

A mi parecer te quedo bien.

**Comment by JuanQ1226** [comment]
@warm007 Estas son las cosas que note:
- Customizable Workouts: 
  Description: Users have the flexibility to create their own workouts, selecting exercises from a library or __designing entirely new ones__. 
esto no se hizo en este milestone. 
Also remove this because of the same reason: "and users can design entirely new exercises using a user-friendly interface." in the Implementation part.
- La parte de achievements tampoco se hizo. 
- TAmbien deberias anadir una seccion de documentation.

**Comment by warm007** [comment]
@JuanQ1226 la sección de documentación seria para cada punto?

**Comment by warm007** [comment]
@JuanQ1226 o seria al final?

**Comment by warm007** [comment]
@JuanQ1226 @gabrielpadilla7 @AlfredoSoto1 La parte de "Achievement System" estaba anteriormente escrita en la documentacion, solo la modifique. Me dejan saber que hago;  si quieren que la borre?

**Comment by JuanQ1226** [comment]
Creo que esto estaria Bien cerca de team requirements antes de validation. Ponlo en una section a parte.

**Comment by JuanQ1226** [comment]
> @JuanQ1226 @gabrielpadilla7 @AlfredoSoto1 La parte de "Achievement System" estaba anteriormente escrita en la documentacion, solo la modifique. Me dejan saber que hago;  si quieren que la borre? 

Ahora pensandolo Creo que Seria mejor que la dejes por eso mismo.

**Comment by warm007** [comment]
Agile Methodology Adoption for Fitness Project
To ensure the successful execution of this fitness project, we are adopting the Agile methodology. Agile's adaptability and responsiveness to changing needs and preferences will guide our development process, breaking the project into smaller, manageable segments or sprints.
Function Segments
1.	Roadmap for Goal-Oriented Progression:
•	Description: The project features a gamified progression system with predefined workouts, serving as a roadmap for users.
•	Purpose: Guides users through sequential workouts, unlocking progressively to simulate a gaming-like progression.
•	Benefits: Users experience a sense of accomplishment, akin to leveling up in a game, fostering motivation and adherence.
•	Implementation: A quick-play option is available, and workouts unlock sequentially based on user progress, encouraging users to complete one to unlock the next.
2.	Customizable Workouts:
•	Description: Users have the flexibility to create their own workouts, selecting exercises from a library, designing entirely new ones or selecting one of the pre-made challenges.
•	Purpose: Provides a high level of customization, allowing users to tailor their fitness experience to individual needs and preferences.
•	Benefits: Users can adapt their fitness routine as their goals evolve, ensuring a unique and dynamic journey.
•	Implementation: The platform offers access to preselected workouts.
3.	Exercise and Workout Management:
•	Description: Users can save selected exercises and entire workout routines, creating a personal library for easy access and reuse.
•	Purpose: Enhances user customization and convenience, enabling efficient organization of their fitness resources.
•	Benefits: Streamlines the fitness journey, making it more organized and user-friendly, ultimately saving users time in planning and execution.
•	Implementation: The platform includes a feature that allows users to save, organize, and reuse their preferred exercises and workout routines.
4.	Achievement System:
•	Description: The project will implement an achievement system, rewarding users for consistency and exercise quantity.
•	Purpose: Motivates users to maintain exercise routines by providing tangible rewards, such as badges and other recognitions.
•	Benefits: Enhances the overall gamified fitness experience, creating a sense of accomplishment and encouraging users to stay engaged and committed.
•	Implementation: Users earn badges and rewards based on achieving fitness milestones, fostering a positive feedback loop.
5.	Engaging User Interface:
•	Description: The platform's user interface is designed to be intuitive and engaging, resembling an interactive gaming experience.
•	Purpose: Enhances user motivation and enjoyment during exercise sessions through a visually appealing and user-friendly interface.
•	Benefits: Features like progress bars and XP tracking provide users with real-time feedback on their fitness journey, creating an immersive and enjoyable experience.
•	Implementation: The user interface incorporates gamified elements, progress tracking tools such as progress bars, and XP indicators to create an immersive and visually appealing fitness environment.

**Comment by warm007** [comment]
@AlfredoSoto1 @JuanQ1226 Verifiquen nuevamente.

**Comment by JuanQ1226** [comment]
Lo veo bien.
