### ISSUE TITLE
Application of topics - Class diagrams [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#114]
# Description

Verificar lo que ya está en la documentación y añadir/mejorar lo que se propone en este issue.
Al finalizar marcar como done este task y el issue de referencia [issue #111]

## Class diagrams, state charts, Petri nets, and/or sequence diagrams
```
The team uses diagrams to _complement_ some descriptions or
explanations in a way such that the text clarifies the diagram and
the diagram clarifies the text. The diagrams are used according to
the purposes of the type of diagram. For example, a class diagram is
used to show the relationship between domain entities. Or a sequence
diagram is used to show interactions between objects when realizing
a specific scenario.
```

- [ ] Done ✅

**Comment by AlfredoSoto1** [comment]
El en issue #111 aparece la rubrica para que se dejen llevar

**Comment by AlfredoSoto1** [comment]
Recuerden, todo lo viejo que se modifique tiene que estar diferenciado a lo nuevo que se añada. Esto puede ser con distintos highliters en el documento.

**Comment by AlfredoSoto1** [comment]
@CristianMatos3 Va a estar ayudandolos en este task. Mantenganse en contacto para que todo esté coherente al momento de someter los cambios que vallan a hacer en la documentación.

**Comment by CristianMatos3** [comment]
@AlfredoSoto1 @gabrielpadilla7 just added some descriptive text for the sequence diagram of section 2.3.1. With this I believe this issue is done, however Id appreciate it if you could review it and let me know if I should change or add anything. Thanks.

**Comment by gabrielpadilla7** [comment]
> @AlfredoSoto1 @gabrielpadilla7 just added some descriptive text for the sequence diagram of section 2.3.1. With this I believe this issue is done, however Id appreciate it if you could review it and let me know if I should change or add anything. Thanks. 

Everything looks good to me, however there is a small spelling mistake on the ERD diagram in the user table, experience points is spelled as "eperience points". Waiting for @AlfredoSoto1 to proofread before closing and marking as done

**Comment by AlfredoSoto1** [comment]
He revisado la documentación en general y la sección 2.3.1, exhorto a que los diagramas en general tanto para esta parte como en el resto del documento que el contenido sea un poco mas apreciable ya sea agrandando la imagen o cualquier otro método. Por otro lado, lo que se añadió entiendo que está highlighted de un color pero debo recalcar que aquello que halla sido modificado (del milestone 1) debe de estar en otro color para que el profe vea que se actualizó dicha parte. En caso de ser **nueva** información debe de ser highlighted con el color que está actualmente.

**Comment by AlfredoSoto1** [comment]
Aquí les dejo la rúbrica de referencia para que comparen si lo que añadieron/modificaron es cumple con lo que el profesor reclama.

![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/108200951/c13761f2-9191-4d2b-a8ab-32d307ee270e)
