### ISSUE TITLE
Application of topics - Alloy/TLA+ [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#115]
# Description

Verificar lo que ya está en la documentación y añadir/mejorar lo que se propone en este issue.
Al finalizar marcar como done este task y el issue de referencia [issue #111]

  • Alloy/TLA+

    The team uses Alloy or TLA+ to specify some relevant aspects related
    to their domain and/or their requirements and then states properties
    that they check with the model checker.  For example, in the library
    specification we can state the property that there are books of
    which some copies are owned by one library and some copies are owned
    by another library. The model checker can them be used on this
    property.

- [ ] Done ✅

**Comment by AlfredoSoto1** [comment]
El en issue #111 aparece la rubrica para que se dejen llevar

**Comment by AlfredoSoto1** [comment]
Recuerden, todo lo viejo que se modifique tiene que estar diferenciado a lo nuevo que se añada. Esto puede ser con distintos highliters en el documento.

**Comment by AlfredoSoto1** [comment]
Aquí les dejo la rúbrica de referencia para que comparen si lo que añadieron/modificaron es cumple con lo que el profesor reclama.

![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/108200951/c13761f2-9191-4d2b-a8ab-32d307ee270e)

**Comment by JuanQ1226** [comment]
Updates on this?

**Comment by JuanQ1226** [comment]
Remember this is for 8pm today.
