### ISSUE TITLE
Application of topics - Other lecture topics

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#116]
# Description

Verificar lo que ya está en la documentación y añadir/mejorar lo que se propone en este issue.
Al finalizar marcar como done este task y el issue de referencia [issue #111]

## Other lecture topics
```
The team documents all applications of lecture topics on their
project, each with a discussion of the benefits initially expected
and with the benefits actually achieved.
```

- [ ] Done ✅

**Comment by AlfredoSoto1** [comment]
El en issue #111 aparece la rubrica para que se dejen llevar

**Comment by JuanQ1226** [comment]
Personas (making them come alive), creo que todos los lecture topics

Improve the presentation of the personas in the documentation

To make it into a character, not have 1 sentence descriptions. 

another lecture topic, we did talk about state charts, petri nets

we talked about petri nets, is there something in your domain, somehow around your project where, that's relevant and is described and has to do with processes and actions taht run in parallel and access shared resources, wehre the resource can only be used exclusively, they can share but only one can access at a time. 

if there's something that is at the core of the domain that you want to describe in TLA+, for example you can take some properties and characteristics of the system or the domain adn characterize that with tla+ and create a property and make the property checked with the model checker. 

we talked about domain fascets, requirements fascets, you can take this as a checklist and to review whether theree are thingsi in the domain that needs to be described that falls into those fascets, same into requirements

In the TLA+ example, there might be several properties of several, different several areas on the domain that you want to stte the properties that can be separately modeled and checked. SO you would not have jut a single lecture task  but multiple

same with petri nets, in the model yo ucan have multiple areas where yo ucan see parallel activities.

**This is an explanation given by the professor.**

**Comment by AlfredoSoto1** [comment]
Recuerden, todo lo viejo que se modifique tiene que estar diferenciado a lo nuevo que se añada. Esto puede ser con distintos highliters en el documento.

**Comment by AlfredoSoto1** [comment]
Recalco una vez más para que no se cometa el mismo error. Recuerden que lo nuevo debe de estar highlighted de un color **DISTINTO** a lo que se valla a modificar del documento (lo del milestone 1). Eso fue unas de las criticas que el profe dejó.

**Comment by AlfredoSoto1** [comment]
Aquí les dejo la rúbrica de referencia para que comparen si lo que añadieron/modificaron es cumple con lo que el profesor reclama.

![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/108200951/c13761f2-9191-4d2b-a8ab-32d307ee270e)
