### ISSUE TITLE
Application of topics - Class diagrams more dev help [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#118]
@CristianMatos3 Va a estar ayudandolos en este task. Mantenganse en contacto para que todo esté coherente al momento de someter los cambios que vallan a hacer en la documentación.

_Originally posted by @AlfredoSoto1 in https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/issues/114#issuecomment-1802759934_

**Comment by AlfredoSoto1** [comment]
El en issue #111 aparece la rubrica para que se dejen llevar

Recuerden, todo lo viejo que se modifique tiene que estar diferenciado a lo nuevo que se añada. Esto puede ser con distintos highliters en el documento.

**Comment by AlfredoSoto1** [comment]
Recalco una vez más para que no se cometa el mismo error. Recuerden que lo nuevo debe de estar highlighted de un color **DISTINTO** a lo que se valla a modificar del documento (lo del milestone 1). Eso fue unas de las criticas que el profe dejó.

**Comment by AlfredoSoto1** [comment]
Aquí les dejo la rúbrica de referencia para que comparen si lo que añadieron/modificaron es cumple con lo que el profesor reclama.

![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/108200951/c13761f2-9191-4d2b-a8ab-32d307ee270e)

**Comment by CristianMatos3** [comment]
> Recalco una vez más para que no se cometa el mismo error. Recuerden que lo nuevo debe de estar highlighted de un color **DISTINTO** a lo que se valla a modificar del documento (lo del milestone 1). Eso fue unas de las criticas que el profe dejó.

Vale. Que color uso para highlight lo nuevo? Seria bueno estandarizar eso para todo el grupo para no tener mas de un color de highlight en distintas partes del documento.

**Comment by AlfredoSoto1** [comment]
Para lo nuevo el color debe de ser el amarillo que se está usando. Para lo que se valla a actualizar/arreglar del **milestone 1** pienso que debe de ser either blue or green. Yo lo voy a mencionar en los demas issues para que lo hagan los que estén trabajando en sus partes.
