### ISSUE TITLE
Documentation Software Design [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#125]
# Description
Completar todos los puntos presentes a continuación. Fecha limite para completar el issue es para antes del 27 de noviembre.
Recuerden que lo que se añada tiene que estar highlighted para que se denote la diferencia eso incluye lo que se valla a mejorar de la documentación que debe de estar highlighted de **otro color** al que se tiene al añadir lo nuevo.

## Software Design
- [x] ✅Done
```
    The team analyzes the requirements and identifies and documents
    components that collaborate to satisfy the requirements. There is at
    least one major business process that the team uses as a scenario to
    validate the design.
```

**Comment by CristianMatos3** [comment]
@AlfredoSoto1 

I added some components that were already implemented and that collaborate with other features to meet the established requirements. I also added a business process which the team used when designing for the user's experience.  Let me know what you think.

**Comment by AlfredoSoto1** [comment]
Perfect, recuerden que mientras vallan completando los tasks, vallan marcando ✅**Done** en el mismo para ir anotando el progreso.

**Comment by CristianMatos3** [comment]
> Perfect, recuerden que mientras vallan completando los tasks, vallan marcando ✅**Done** en el mismo para ir anotando el progreso. 
> 
> 

Ya esta 🫡

**Comment by LightPolution** [comment]
Done!
