### ISSUE TITLE
Documentation Domain Requirements [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#126]
# Description
Completar todos los puntos presentes a continuación. Fecha limite para completar el issue es para antes del 27 de noviembre.
Recuerden que lo que se añada tiene que estar highlighted para que se denote la diferencia eso incluye lo que se valla a mejorar de la documentación que debe de estar highlighted de **otro color** al que se tiene al añadir lo nuevo.

## Domain Requirements
- [x] ✅Done
```
      The team identifies domain requirements from domain
      properties. For example, in a project concerned with libraries,
      books, borrowing, … there is a domain property that every book has
      an owner. When the team then moves on to determine requirements
      and the focus is only on libraries (not e.g. the books a patron
      might otherwise own), we get a domain requirement: the
      system-to-be must associate with each book exactly one library as
      the owning library.
```

**Comment by AlfredoSoto1** [comment]
Recuerden que lo que se modifique en el documento tiene que ser de un color distinto a lo nuevo que se añada.

**Comment by AlfredoSoto1** [comment]
Aqui les dejo el link al documento para que puedan actualizarlo
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by AlfredoSoto1** [comment]
Recuerden que mientras vallan completando los tasks, vallan marcando ✅**Done** en el mismo para ir anotando el progreso.

**Comment by Chosen-Juan1** [comment]
Added the following to the document (in the domain requirements section):

- The system shall allow users to create their own type of exercise and allow them to store these creations in workout routines.
- The system must allow users to share these customized workouts with other users.
- The system shall allow users to interact with each other within designated social areas.

**Comment by Chosen-Juan1** [comment]
They are based on what was added last time to the derived goals section.

**Comment by Chosen-Juan1** [comment]
Reading what was already in the documentation, and considering what I added, I believe that this issue is completed.

**Comment by edgaelm** [comment]
Added requirements: 
The system shall allow exerciser to select a goal, either loose weight, gain muscle, strength, cardio or calisthenics.
The system shall provide a specific routine for the goal the exerciser decided to achieve.
The system shall provide specific workout routines depending on the environment the workouts are taking place.
The system shall provide specific workout routine depending on the available equipment.
The system shall provide challenges to provide more engagement, motivation and consistency.
