### ISSUE TITLE
Documentation Interface Requirements [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#127]
# Description
Completar todos los puntos presentes a continuación. Fecha limite para completar el issue es para antes del 27 de noviembre.
Recuerden que lo que se añada tiene que estar highlighted para que se denote la diferencia eso incluye lo que se valla a mejorar de la documentación que debe de estar highlighted de **otro color** al que se tiene al añadir lo nuevo.

## Interface Requirements
- [x] ✅Done
```
      The team analyzes and documents the shared data initialization and
      update requirements, the man-machine and the machine-machine
      dialog requirements, and the physiological requirements.
```

**Comment by AlfredoSoto1** [comment]
Recuerden que lo que se modifique en el documento tiene que ser de un color distinto a lo nuevo que se añada.

**Comment by AlfredoSoto1** [comment]
Aqui les dejo el link al documento para que puedan actualizarlo
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by Chosen-Juan1** [comment]
for the shared data initialization, i have made this graph
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/101728824/63cb93df-500a-4bdc-bca9-f33127d9b1b5)
In the document, i shall elaborate further on the steps.

**Comment by Chosen-Juan1** [comment]
"For the shared data update facet, we consider the events when we need to update our shared date. These events might be when: the user gains experience or a new level, when the user makes a new exercise, when the user completes a level in the road map, or when the user gains an achievement. All of these events entail an update to the data that was previously stored, so they are sent to the database."

**Comment by Chosen-Juan1** [comment]
added this bit for the shared data update facet

**Comment by Chosen-Juan1** [comment]
"For the man-machine dialogue requirements, the system must provide clear communications when addressing the user. This applies includes, but is not limited to, the following scenarios: When providing the user instructions, when providing status updates of ongoing processes, when providing the user with updates to their profile (like when they reach a new level in the road map or when they gain a reward/achievement)." added this for man-machine dialogue.

**Comment by Chosen-Juan1** [comment]
"In the case of machine-machine dialogue, the system must provide and store all information using a specific format so that it may be stored in the database without causing problems." added this for machine-machine dialogue.

**Comment by Chosen-Juan1** [comment]
"Finally, for the physiological requirements, the system must indicate the user’s progress towards the next level using a green progress bar. It first starts off gray, but is filled with a green color that symbolizes how much progress the user has made towards their new level" added this for physiological requirements.

**Comment by Chosen-Juan1** [comment]
Since i have completed the last point, I'm going to mark this task as done, but if other assignees have corrections or more information to add, please feel free to do so.
