### ISSUE TITLE
Documentation Petri Nets [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#129]
# Description
Completar todos los puntos presentes a continuación. Fecha limite para completar el issue es para antes del 27 de noviembre.
Recuerden que lo que se añada tiene que estar highlighted para que se denote la diferencia eso incluye lo que se valla a mejorar de la documentación que debe de estar highlighted de **otro color** al que se tiene al añadir lo nuevo.

## Petri Nets
- [x] ✅Done
```
    The team uses Petri nets (place transition nets) to model competing
    processes that access common resources. It's not necessary to have a
    complete model but we want to see at least some are competing
    activities.
```

**Comment by AlfredoSoto1** [comment]
Recuerden que lo que se modifique en el documento tiene que ser de un color distinto a lo nuevo que se añada.

**Comment by AlfredoSoto1** [comment]
Aqui les dejo el link al documento para que puedan actualizarlo
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by AlfredoSoto1** [comment]
Recuerden que mientras vallan completando los tasks, vallan marcando ✅**Done** en el mismo para ir anotando el progreso.

**Comment by misaelmercado1** [comment]
Petri net for the fitquest project completed
