### ISSUE TITLE
Documentation Business Processes [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#130]
# Description
Completar todos los puntos presentes a continuación. Fecha limite para completar el issue es para antes del 27 de noviembre.
Recuerden que lo que se añada tiene que estar highlighted para que se denote la diferencia eso incluye lo que se valla a mejorar de la documentación que debe de estar highlighted de **otro color** al que se tiene al añadir lo nuevo.

## Business Process
- [x] ✅Done
```
  The team describes at least one relevant and substantial business
  process from the domain for each stakeholder group.
```

**Comment by AlfredoSoto1** [comment]
Recuerden que lo que se modifique en el documento tiene que ser de un color distinto a lo nuevo que se añada.

**Comment by AlfredoSoto1** [comment]
Aqui les dejo el link al documento para que puedan actualizarlo
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by AlfredoSoto1** [comment]
Recuerden que mientras vallan completando los tasks, vallan marcando ✅**Done** en el mismo para ir anotando el progreso.

**Comment by Chosen-Juan1** [comment]
Este es mi ejemplo para el business process basado en la presentación de Shutz:
Stakeholder: FitQuest user
Process: Download the app, participate in pre-made activites, generate custom workouts.

**Comment by Chosen-Juan1** [comment]
este es otro:
Stakeholder: Health and Fitness Professionals
Process: Participate in reunions with Fitquest development team for consultations, download the app, 
judge contents in app, provide feed back for developers.

**Comment by Chosen-Juan1** [comment]
I made a Business Processes section on the document so that we may add this task's information to the documentation.

**Comment by Chosen-Juan1** [comment]
added the following processes:
Stakeholder: Developers and Technical Team	
Process: Read issues on github, attempt to solve said issues, report progress, test application, document progress.

Stakeholder: Marketing and Sales
Process: Market application, promote application, research competition, research user interest.

Stakeholder: Customer Support
Process: Receive user feedback, attempt to aid users in solving problems, document problems.

**Comment by Chosen-Juan1** [comment]
Since i have mentioned the more relevant stakeholders (related to the project) i shall mark this issue as complete.
