### ISSUE TITLE
Documentation Personas [Lecture Topic Task]

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#132]
# Description
Completar todos los puntos presentes a continuación. Fecha limite para completar el issue es para antes del 27 de noviembre.
Recuerden que lo que se añada tiene que estar highlighted para que se denote la diferencia eso incluye lo que se valla a mejorar de la documentación que debe de estar highlighted de **otro color** al que se tiene al añadir lo nuevo.

## Personas
- [x] ✅Done
```
The team has developed personas that are detailed beyond merely
      their user-stories, so the persona really comes alive.
```

**Comment by edgarsuarez123** [comment]
Fitness Enthusiast Emma:

Name: Emma
Age: 28
Job: Marketing Professional
Location: San Francisco, CA
Bio: Emma is a marketing professional who discovered her passion for fitness during college. Juggling a demanding job and an active social life, she values a fitness app that tracks workouts, introduces new exercises, and supports her balanced lifestyle.
Goals: Efficiently track workouts, discover new exercises, monitor nutrition.
Marital Status: Single
Fitness Level: Intermediate
Challenges: Balancing work and social life, staying motivated.
Newbie to Fitness Noah:

Name: Noah
Age: 35
Job: Accountant
Location: New York City, NY
Bio: Noah, an accountant, recently started his fitness journey. Seeking a user-friendly app, he wants guidance on basic exercises and aims to establish a consistent workout routine. Noah is determined to adopt healthier habits.
Goals: Establish a consistent workout routine, receive guidance on exercises, develop healthy habits.
Marital Status: Single
Fitness Level: Beginner
Challenges: Overcoming gym intimidation, understanding a healthy diet.
Weight Loss Warrior Olivia:

Name: Olivia
Age: 40
Job: Teacher
Location: Austin, TX
Bio: Olivia, a teacher, is committed to her weight loss journey. Balancing work and family, she seeks a fitness app with personalized workout plans to track calories and nutrition. Olivia aims to make sustainable lifestyle changes.
Goals: Lose weight, personalized workouts, track calories.
Marital Status: Married
Fitness Level: Intermediate
Challenges: Balancing work and family, maintaining a healthy diet.
Senior Fitness Explorer Samuel:

Name: Samuel
Age: 65
Job: Retiree
Location: Miami, FL
Bio: Samuel believes in staying active for overall well-being. As a senior, he looks for a fitness app with low-impact workouts and health metric monitoring. Samuel adapts his routine to age-related limitations while maintaining an active lifestyle.
Goals: Stay active, low-impact workouts, monitor health metrics.
Marital Status: Married
Fitness Level: Beginner to Intermediate
Challenges: Adapting to age-related limitations.
Busy Mom Fitness Fanatic Mia:

Name: Mia
Age: 32
Job: Stay-at-home mom
Location: Denver, CO
Bio: Mia, a fitness fanatic and stay-at-home mom, manages childcare and household tasks. Relying on a fitness app with quick home workouts, she sees fitness as a way to manage stress and encourages her family to embrace healthy habits.
Goals: Quick home workouts, stress management, family health.
Marital Status: Married
Fitness Level: Advanced
Challenges: Balancing childcare, maintaining an active lifestyle.

**Comment by warm007** [comment]
**Adventure Seeker Alex**
Name: Alex
Age: 24
Marital Status: Single
Job: Outdoor Adventure Guide
Location: Boulder, CO
Bio: Alex, an outdoor adventure guide, is passionate about staying fit for outdoor activities. Seeking a fitness app that aligns with an adventurous lifestyle, Alex wants customizable workout plans and nutrition tracking to enhance overall performance.
Goals: Enhance outdoor performance, customizable workouts, nutrition tracking.
Fitness Level: Advanced
Challenges: Maintaining fitness for outdoor adventures, adapting to unpredictable schedules.

**Corporate Professional Chris**
Name: Chris
Age: 30
Marital Status: Single
Job: Corporate Finance Analyst
Location: Chicago, IL
Bio: Chris, a corporate finance analyst, aims to integrate fitness into a sedentary work life. Seeking a time-efficient app, Chris wants quick and effective workouts, stress management features, and the ability to seamlessly fit exercise into a busy schedule.
Goals: Time-efficient workouts, stress management, integrate fitness into work routine.
Fitness Level: Intermediate
Challenges: Balancing work commitments, fitting exercise into a busy schedule.

**Rehabilitation Warrior Riley**
Name: Riley
Age: 45
Marital Status: Divorced
Job: Physical Therapist
Location: Seattle, WA
Bio: Riley, a physical therapist, is recovering from an injury and seeks a fitness app for rehabilitation. Looking for tailored exercises, progress tracking, and expert guidance, Riley wants to regain strength and mobility safely.
Goals: Rehabilitation, tailored exercises, progress tracking.
Fitness Level: Varied (recovering from injury)
Challenges: Safely recovering from injury, adapting workouts to rehabilitation needs.

**Social Connector Sasha**
Name: Sasha
Age: 29
Job: Event Planner
Location: Los Angeles, CA
Bio: Sasha, an event planner, values social interactions in fitness. Looking for an app with community features, group challenges, and social integration, Sasha seeks motivation through shared experiences and friendly competition.
Goals: Social fitness, community engagement, group challenges.
Marital Status: In a relationship
Fitness Level: Intermediate
Challenges: Finding motivation through social connections, maintaining a consistent routine.

**Mindful Meditator Max**
Name: Max
Age: 38
Job: Psychologist
Location: Portland, OR
Bio: Max, a psychologist, values the connection between mental and physical well-being. Seeking a holistic fitness app, Max wants mindfulness features, meditation exercises, and a focus on overall wellness to achieve a balanced and healthy lifestyle.
Goals: Mindful fitness, meditation exercises, overall wellness.
Marital Status: Married with children
Fitness Level: Intermediate
Challenges: Balancing work, family, and personal well-being, integrating mindfulness into daily routine.

**Comment by warm007** [comment]
Saludos, @AlfredoSoto1 @gabrielpadilla7 @JuanQ1226 ! Adjunto, la documentación de Personas. Si alguno la puede revisar y nos dejan saber que les parece o si necesita que le añadamos algo más. Cuando nos den visto bueno, la subimos al Google Docs!

**Comment by JuanQ1226** [comment]
Yo la veo super, tiene más detalle que es lo que el profe quiere. Lo dijo aquí : _Personas have a specific purpose: to give everybody around the project magic powers in wielding all that is identified with the persona by just evoking the persona's name. Your personas are described with too little detail, one cannot really see a vivid picture of a person. Please read up on the use of personas, not just in the area of software engineering, but also in other areas._

**Comment by gabrielpadilla7** [comment]
Se ve excelente! Como dijo Juan tiene mas detalle de lo que necesita el profesor, un poco de modificaciones y creo que despues de eso se puede add desde ya al documentation.

**Comment by warm007** [comment]
Ok, nos dejamos llevar del ejemplo que aparece en los Slides "Domain Engineering and Domain Facets". Este era el link de ejemplo: https://library.xtensio.com/software-developer-persona-example

**Comment by AlfredoSoto1** [comment]
Aqui les dejo el link al documento para que puedan actualizarlo
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing
