### ISSUE TITLE
Sign up/Login screen (tie in)

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#135]
Issues #103 and #107 have both the front and the backend of the sign up and login screen

For this issue, you must communicate as a team between both front end and back end to see how everything will interconnect with each other. This is important for the functionality of the software. 

The following checklist is added for clarity, if there is something that is missing feel free to let me know and I will add it to the list

**Sign up screen**

- [ ] The user must be able to input their information, such as name, age, etc mentioned in the sigun up section of issue #103. 
- [ ] The information must be stored in the database. 

**Login screen**

- [ ] The user must be able to input their email and password
- [ ] The program must verify that the email is in the database
- [ ] If the email is in the database, check if the password matches. If the password doesn't match with that email, the user CANNOT access the program with their profile. 

Communication between both front end and back end is vital for this issue.

**Comment by JorgeC08** [comment]
Ya creo que tengo la pagina principal del Login y Signup. Falta enlazarlo con el backend y ponerlo bonito.  También se podría poner algo que pueda corroborar que es un email (si es que se puede y es necesario) porque hasta el momento cualquier cosa sirve para hacer login y signup. El mismo lo subí en un nuevo branch llamado 'signup-login-screen'.

Ya en ambas, LoginScreen.tsx y en SignUpScreen.tsx tienen funciones que se supone que sea para manejar la lógica de autentificar si el usuario existe. Falta añadirle la lógica.

**Comment by JorgeC08** [comment]
Saludos ¿han podido hacer algo? 

Estos dos días he estado en el trabajo y no he podido ver si hay algún update.

**Comment by JuliT02** [comment]
Yo puedo trabajar en el despues de trabajar en el Milestone 3 documentation que cierra el lunes

**Comment by Chosen-Juan1** [comment]
> Saludos ¿han podido hacer algo?
> 
> Estos dos días he estado en el trabajo y no he podido ver si hay algún update.

Ahora mismo, ya logre hacer la parte que envia la informacion de front end a backend. lo que esta dando problemas son unos import errors desde backend que estoy intentando solucionar.
