### ISSUE TITLE
Final presentation

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#136]
# Description
Prepare a video proposal containing the new features set for the last milestone. This video must be like the video proposal of the last two milestones but with all the feedback from the professor given in moodle. This video must be around the same length as the other proposals. For this task we need the following:

- [x] Write a script
- [x] Record a demo of the video
- [x] Record the video
- [x] An improved version of the presentation with the professor's feedback (from milestone 2)
- [x] Build on top the updated presentation, new information about the last milestone

Here is the link of the documentation in case you need it for reference.
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

# Recording and Presentation

- We are in need of an individual with proficient presentation abilities who can confidently deliver our script. Strong communication skills are vital for this task.

# Video Editing

- After the recording, we require a skilled video editor who can craft a polished and professional video presentation.

# YouTube Management

- Prepare and upload the video to youtube and create a link that can be shared with the professor.

**Comment by Jeimy-S** [comment]
https://docs.google.com/presentation/d/1SDDZb4rVvmGV6H48nBXXcm41uroqNvPizdK7qS8tBZI/edit?usp=sharing
