### ISSUE TITLE
Prepare Video script

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#137]
# Description
En colaboración con el [Issue #136],  preparar un script detallado para el que valla a presentar el proyecto en el video. Este script debe hablar del proyecto completo en sí. Importante que para este issue tambien se trabaje con la presentación de los milestones pasados. Para este se debe mostrar todo acerca del proyecto.

### Importante
Enfatizo aquí que cualquier cosa que se valla a presentar en la presentación como diagramas o imágenes, estas deben ser claramente visibles al momento de presentar.

**Comment by Chosen-Juan1** [comment]
[Milestone3Script.docx](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/files/13501093/Milestone3Script.docx)
[FitQuest Proposal Presentation.pdf](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/files/13501106/FitQuest.Proposal.Presentation.pdf)
Script and presentation that are going to be used in video.
