### ISSUE TITLE
Prepare video presentation

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#138]
# Description
Grabar y editar el video, este puede durar alrededor de 15 minutos así como se hizo para los milestones pasados. Importante mantener contacto con los del Issue #136 donde se habla de manera general de cada parte para este video proposal.

**Comment by Jeimy-S** [comment]
https://docs.google.com/presentation/d/1SDDZb4rVvmGV6H48nBXXcm41uroqNvPizdK7qS8tBZI/edit?usp=sharing

**Comment by Chosen-Juan1** [comment]
https://docs.google.com/presentation/d/12HNQd-Nae-_YHOrwbsATWdglTXflUgjesBco4ZdB_WY/edit?usp=sharing

**Comment by Chosen-Juan1** [comment]
Presentation for milestone 3
