### ISSUE TITLE
Prepare a demo for video

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#139]
# Description
Preparar un Demo de la aplicación que muestre todos los aspectos del software. Es importante tener en mente que el demo debe de mostrar toda la aplicación pero enfatizar lo más importante del programa (Domain). Para este Issue es importante mantener contacto continuo con los que van a hacer el script y grabar el video para la presentación como tal en los Issues[#137] y [#138] respectivamente.

**Comment by edgaelm** [comment]
Se realiza Demo de video para milestone 3: https://drive.google.com/file/d/1R8fV7mjm0Ccn9TmzfJ3fzN2rLPJRCxPZ/view?usp=sharing

**Comment by edgaelm** [comment]
Se puede marcar esta tarea como Done
