### ISSUE TITLE
Setup React Native Project / Initial Commit

### ISSUE THREAD

**Issue by JuanQ1226** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#2]
# Create the Initial React Native Project -> Team 2
#### Create the react native project using the terminal
- **Must have NodeJS LTS version installed**
- Create a new branch
- run: `cd Frontend`
- run : `npx create-expo-app FitquestApp`
- commit and push your branch and then make a pull to the beta branch request in github.
---
## Priority 10 * Difficulty 1 = 10 Task points

**Comment by JuanQ1226** [comment]
@warm007  You we're selected randomly. Any doubts contact me.

**Comment by oscaroflores** [comment]
npx done
pull request done

**Comment by JuanQ1226** [comment]
@oscaroflores succesfully setup the project.
