### ISSUE TITLE
Design Timer (and code it) -> Team 3

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#21]
Design how the timer should look like, and how the user should interact with it. 

- [x] User must be able to see the time
- [x] User must be able to stop, cancel and skip the timer
- [ ] The user must be able to skip the timer and go into the cooldown using a button and vice versa
- [x] The user must be able to pause and play the timer
- [x] There must be a video or gif at the bottom explaining how to do the exercise (for the design process this could just be an image or a simple square)
- [ ] The skip button must have a small design at the bottom designating if it's in cooldown or exercise mode at the moment (denoted by a snowflake for cooldown and a fire for the exercise mode)
- [ ] There must be a back button to go to the main menu 

### You can use figma for the design process

**Comment by gabrielpadilla7** [comment]
![20230918_172958](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/112046903/ce3508a7-f3c0-45db-af3a-2b0265babf53)


I'm adding a sketch of what we did in today's reunion so that it can be done something like this, but of course a lot better and cleanly designed, it's just the base of the timer. 

I will add some more checks for newer specifications

**Comment by CristianMatos3** [comment]
Hi! I just finished updating the timer's design as we discussed on Monday. As you can see in the image provided, the timer is now more visually appealing. I've also added base templates for the workout info which include counters for the current repetition and set of the workout being performed as well as a blank space provided to insert the corresponding GIF or YouTube hyperlink. Any feedback or recommended changes are more than welcome. @gabrielpadilla7 


![Timer update](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/98779476/82f19bba-a13d-43c5-8579-b03e23f33bfa)

**Comment by gabrielpadilla7** [comment]
Looks amazing! However the reset button should be a skip button, as that button will allow the user to skip the current time of the workout and go straight to cooldown and vice versa. If possible, under that button, please add a design for the current state (example, if you're in workout mode, the button shows at the bottom inside a fire, if you're in cooldown mode, it shows a snowflake). The design is also missing a back button which will be at the top left corner of the screen. The reset button can be put where stop is, and the start button can have 2 states, a play and pause state (similar to how the skip button changes depending if you're in cooldown mode or workout mode). In the original sketch it's denoted with an arrow. 

If you have any doubts about the instructions please let me know through here or Discord! @CristianMatos3

**Comment by gabrielpadilla7** [comment]
EDIT: Heard that not only were y'all desigining the timer but you also were coding it. For this reason, I will edit the title and increase the difficulty on this issue (more points)
