### ISSUE TITLE
Research workouts -> Team 3

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#22]
Research workouts and workout categories. The application should show the user what workouts to do depending on the area of the body they want to work on. 

For this, compile a series of "packages" of workouts

Example:

Leg workouts include: X workout for x amount of time, Y workout with y amount of time, etc...

**Comment by JuanQ1226** [comment]
You could also look how many calories/per minute each exercise consumes.

**Comment by JorgeC08** [comment]
> You could also look how many calories/per minute each exercise consume

Yes I could look into it. Having answered some question on monday. If anything pops up I'll put it here

**Comment by gabrielpadilla7** [comment]
This issue was moved to done, if everything is done, please confirm here so that I can close the issue!
