### ISSUE TITLE
Create a visualization for the timer feature

### ISSUE THREAD

**Issue by JuanQ1226** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#24]
## Create a flowchart describing how the timer processes look

The timer will have to meet these requirements:
- Allow the user to input a custom time interval, Including hours, minutes and seconds.
- Allow the user to select between 3 predetermined time interval (1 min, 2 min, 30 min).
- Count down to the selected interval.
- When the interval is finished throw and alert.
- When **Reset** button is pressed reset and stop the timer to `00:00:00.000` 
- When **Stop** button is pressed pause the time without resetting it.
- When the **Start** Button is pressed start the timer.
- In the timer page there must be a _Workout_ that when pressed it fetches workouts stored in our database and displays them to the user.
- When a workout is selected all the exercise intervals of the corresponding workout will be queued for the timer to count down.
- There must be a _Cancel Workout_ that when pressed it will clear the _Workout queue_ and reset the timer.
---

Upload the diagram as an image here when done.

_Note: Use a flowchart making software such as excalidraw or others._

**Comment by marcosarraiza** [comment]
![flowchart inso png](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/94330664/8bf60ab6-1581-40fa-84cb-c34761021198)
Created the flowchart for the timer

**Comment by JuanQ1226** [comment]
Añade la parte de cuando hace el fetch de los databases. Abunda más para que los backend puedan entender que hacer.

**Comment by marcosarraiza** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/94330664/6df6c169-7cd0-4536-b0ca-2c63473ccc21)
Resolved comment
