### ISSUE TITLE
Structure Queries using SQL

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#34]
- [ ] Learn the basics of SQL language
- [ ] Design/develop pseudo code on basic queries on how to select data from database
- [ ] Design/develop pseudo code on basic queries on how to insert data from database

**Comment by Chosen-Juan1** [comment]
For this task, we could split the pseudo codes between us. @JuliT02 do you wish to do the data selection task or the data insertion task? I’m fine with either.
