### ISSUE TITLE
Database table content structure

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#35]
Design database to hold the following contents:

- [x] Name of workout
- [x] Set of available exercises inside the workout

Exercises themselves need:
- [x] Name of exercise
- [x] Duration in seconds/minutes
- [x] Instructions / description of the exersise
- [x] Link of a gif or an image of the exercise

**Comment by misaelmercado1** [comment]
Receeived

**Comment by GregAlexander07** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/37248454/d866d195-5186-40d3-9a18-e95de1c2659a)

this is how the database schema looks like so far
currently working on a solution for the redundancy of the many workout related tables

**Comment by GregAlexander07** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/37248454/222538cb-3b90-4bd8-a2ff-c2bb20ce51f4)

updated the diagram since roadmap_workouts will have a relationship with the predefined_workouts and not the user_workouts

**Comment by GregAlexander07** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/37248454/40e52783-de31-4cea-9bc5-55086bde4338)

adjusted the exercise table
