### ISSUE TITLE
Implement Custom Workout Creation page

### ISSUE THREAD

**Issue by JuanQ1226** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#36]
#### The Custom Workout page will need to meet these requirements:
- [x] When first entered the page has to present different exercise categories (Arms,legs,...). When the user chooses one the exercises of the category are displayed.
- [x] The system has to allow the user to input a custom duration time to the particular exercise. (In minutes, which are saved as miliseconds)
- [x] The exercises have to be chosen with a checkbox or similar that allow multiple selection.
- [x] After the user selects the exercises and presses a confirm button display all the selected exercises in a list.
- [x] Allows the user to input a name for the workout.
- [x] Show a confirm button that when pressed the created workkout gets appended to the array of workouts at `./assets/workoutData.ts`
- [x] We need to add some kind of validation to make sure to take valid times and that the workout is not empty.

If you feel like more fields are needed in the dummy data example feel free to add them. I f you think more features should be added please do so.

**Comment by JuanQ1226** [comment]
I recommend you split this into smaller tasks.

**Comment by oscaroflores** [comment]
El timer va a iterar por los workouts localizados en el Workout[] array del file de /assets/workoutData.ts. 

Les pidos que cuando los users creen workouts nuevos, los mismos se guarden al Workout[] array localizado en el file de /assets/workoutData.ts.

De esta manera, cuando merge los branches a beta, el timer y el custom workout creation feature funcinen en conjunto.

Gracias

**Comment by JuanQ1226** [comment]
Some exercises have been added to `./assets/exerciseData.ts`
