### ISSUE TITLE
Workout creator design

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#38]
The workout creator will allow the user to create their own workouts

The workout creator screen must have the following/allow the user the following:

- [x] The workout creator must allow the user to input the name of their workout
- [x] The workout creator must allow them to set the reps of the workout
- [x] It must allow them to set the time required for the workout
- [x] It must allow them to set the cooldown time of the workout 

You will be using Figma for the design. I've attached a pdf of a sketch of how it should look like, but it should be much more presentable for the user. 

NOTE: you can change this design however you'd like, however this is just the sketch to have an idea how it looks like. The + and - signs in the times can be swapped around if you so desire. 

[workout_creator_sketch_.pdf](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/files/12677705/workout_creator_sketch_.pdf)

**Comment by LightPolution** [comment]
Workout Creator Design - Complete

![Workout Creator Design - Draft 1](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/99355471/92b72e3b-2c55-47c4-b3d1-80ab18a1b2e0)

- button functions must be coded in IDE

**Comment by gabrielpadilla7** [comment]
Design completed. Closing issue.
