### ISSUE TITLE
Implement Workout to timer feature -> Team 2

### ISSUE THREAD

**Issue by JuanQ1226** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#39]
These are the requirements for this task:
- [x] Display Created Workouts on the workout page.
- [x] At the bottom of the expanded workout add a start button.
- [x] When a workout is pressed, expand it and display all the exercises.
- [x] When the start button is pressed load the workout into the timer.
- [x] The timer will only have a start / pause button and a skip button.
- [x] The timer will follow the design specifications on the #21  issue

**Comment by JuanQ1226** [comment]
@oscaroflores feel free to divide this into more task and delagate those to other memebers.

**Comment by IvanierB** [comment]
Hey, por que este task sigue open?

**Comment by JuanQ1226** [comment]
Lo puedes cerrar.
