### ISSUE TITLE
Research Timer npm packages for react native / how to make a functional one -> Team 2

### ISSUE THREAD

**Issue by JuanQ1226** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#4]
# Research how to make a timer in react native
- Look on the internet on how to make an stopwatch or timer on react native.
- Remember we only care about the logic behind the stopwatch. Ignore all the styling, leave it to the frontend guys 😄.
- Make a report enlightening us about your findings, and send it through here, include links, videos you found and sources. Preferably you guys should make one report between the three.

**Note: if you find a plain react package it will not work with react native.**

**Comment by JuanQ1226** [comment]
Use this google doc: https://docs.google.com/document/d/1p5U9GiZpz28jOwKcCsIOhdyZ6KUvkJXFOtAPZeSHQ9Q/edit?usp=sharing

When export it as a pdf and upload it here.

**Comment by edgarsuarez123** [comment]
[Timer Research Report.pdf](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/files/12569415/Timer.Research.Report.pdf)
