### ISSUE TITLE
1-> Informative-Part (2)

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#45]
More deatails on each field in the Documentation Guidelines on moodle

This part of the documentation requires the following:

- [x] 1.4 Other activities than just developing source code
- [x] 1.5 Derived goals

**Comment by AlfredoSoto1** [comment]
Here is the link of the google doc so that you can paste what you are working on

https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by misaelmercado1** [comment]
Other activies than just developing the source code completed

**Comment by Chosen-Juan1** [comment]
Derived goals completed.
