### ISSUE TITLE
2-> Descriptive part (1)

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#46]
More deatails on each field in the Documentation Guidelines on moodle

This part of the documentation requires the following:

- [x] 2.1 Domain Description
- [x] 2.1.1 Domain rough sketch
- [x] 2.1.2 Terminology
- [x] 2.1.3 Domain terminology in relation to domain rough sketch

**Comment by AlfredoSoto1** [comment]
Here is the link of the google doc so that you can paste what you are working on

https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by edgaelm** [comment]
Se completa el diagrama de "Domain Rough Sketch" y "Domain terminology in relation to domain rough sketch" en base a information relacionada a aplicacion FitQuest.


2.1.1 Domain rough sketch:
![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/78558623/344cb7d0-d8f8-4bfe-99dd-88f3ed69a105)


 2.1.3 Domain terminology in relation to domain rough sketch:

1. Player:
   - Individual who uses the application to engage in workouts, track progress, set goals, and participate in gamified elements.

2. Workouts:
   - Workouts encompass the specific exercise routines and physical activities that users engage in to improve their fitness levels, strength, flexibility, or overall health.

3. Motivation:
   - Motivation in the app context refers to the encouragement, inspiration, or incentives provided to users to maintain their workout routines and achieve their fitness goals.

4. Game Aspect:
   - Gamified features, challenges, or interactive elements designed to make the workout experience more engaging and enjoyable for users.

5. Rewards:
   - Rewards are incentives or achievements that users earn as a result of completing workouts, achieving fitness milestones, or participating in challenges. These can include badges, points, or virtual items.

6. Challenges:
   - Challenges are specific goals, tasks, or competitions set within the app to encourage users to push their limits and achieve specific fitness objectives.

7. Environment:
   - Setting in which workouts take place. It can simulate various locations such as a gym, house, or customized settings.

8. House:
   - Location where users engage in fitness activities in their own home.

9. Equipment Availability:
   - Availability of exercise equipment, such as weights, resistance bands, or specialized machines, that users can utilize during their workouts.

10. Gym:
    - Location where users can access a variety of exercise equipment and engage in fitness activities.

11. Types of Workouts:
    - These are different categories or genres of exercises that users can choose from based on their fitness goals and preferences.

12. Calisthenics:
    - Calisthenics involves exercises that use one's own body weight for resistance, such as push-ups, squats, and planks.

13. Weightlifting
    - This category includes exercises that involve lifting weights, such as dumbbells or barbells, to build strength and muscle.

14. Strength Training:
    - Strength training focuses on exercises designed to increase muscle strength, endurance, and power.

15. Muscle Building:
    - Strength training focuses on exercises designed on increasing muscular strength and size.

16. Cardiovascular Activities:
    - Cardiovascular activities are exercises that aim to improve the heart and lung health, such as running, cycling, and swimming.

17. Personalized Exercises:
    - These are workouts tailored to an individual user's fitness level, goals, and any specific preferences or restrictions they may have.

18. User Added Workouts:
    - Allows users to create and customize their own workout routines based on their preferences and specific fitness objectives.

19. Engagement:
    - Engagement refers to the level of involvement, interaction, and interest that users have with the app, including their participation in workouts, challenges, and social features.

20. Goals:
    - Goals are specific fitness objectives that users set for themselves, such as weight loss, muscle gain, improved endurance, or achieving a certain level of fitness proficiency.

**Comment by RicardoGarciaSuarez** [comment]
Just completed the task 2.1.2 Terminology please leaders check and review it, it is still open for changes!
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?pli=1
That's the link for the google documentation where the terminology is located.

**Comment by JorgeC08** [comment]
> Just completed the task 2.1.2 Terminology please leaders check and review it, it is still open for changes! https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?pli=1 That's the link for the google documentation where the terminology is located.

Just checked, changed some miscellaneous but looks good.
