### ISSUE TITLE
2 -> Descriptive part (2)

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#47]
More deatails on each field in the Documentation Guidelines on moodle

This part of the documentation requires the following:

- [x] 2.1.4 Narrative
- [x] 2.1.5 Events, actions, and behaviors
- [ ] 2.1.6 Function signatures

**Comment by AlfredoSoto1** [comment]
Here is the link of the google doc so that you can paste what you are working on

https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by misaelmercado1** [comment]
Going to start working on 2.1.5

**Comment by misaelmercado1** [comment]
2.1.4 done

**Comment by marcosarraiza** [comment]
Worked on 2.1.5
