### ISSUE TITLE
2-> Requirements (3)

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#48]
More deatails on each field in the Documentation Guidelines on moodle

This part of the documentation requires the following:

- [x] 2.2.1 user stories, epics, features
- [x] 2.2.2 personas

**Comment by AlfredoSoto1** [comment]
Here is the link of the google doc so that you can paste what you are working on

https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by JuanQ1226** [comment]
I did the user stories, epics and features.

**Comment by LightPolution** [comment]
Completed User Stories, Epics, and Features, as well as Personas.
