### ISSUE TITLE
3-> Analytic-Part

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#51]
More deatails on each field in the Documentation Guidelines on moodle

This part of the documentation requires the following:

- [x] 3.1 concept analysis
- [x] 3.2 validation and verification

**Comment by JoelTorres20** [comment]
Finished adding the analytical part to the Documentation

**Comment by AlfredoSoto1** [comment]
Review documentation. If it's approved the issue will be closed and marked as done feature.
