### ISSUE TITLE
Setup Docker

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#53]
- [x] Setup docker in your machine to start setting up the database
https://docs.docker.com/

For mac:
https://docs.docker.com/desktop/install/mac-install/

https://docs.docker.com/registry/recipes/osx-setup-guide/

For Windows:
https://docs.docker.com/desktop/install/windows-install/

Small tutorial:
https://www.youtube.com/watch?v=-y1BmDbcaEU

**Comment by GregAlexander07** [comment]
Docker and Docker desk top are installed on my computer 
Any body that has done the set up leave a similar comment and or any issues regarding instalation

**Comment by misaelmercado1** [comment]
Docker along with data grip has been installed on my computer

**Comment by oscaroflores** [comment]
Same here!
