### ISSUE TITLE
Write a script for the video proposal

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#58]
Prepare a script that talks about all the features/goals to be achieved for this project. This also includes strategies, possible algorithms and data structures that can be used or are used to implement a feature. It must also present what we have achieved so far and the future plans for this application. A demo of the application is a must.

Documentation also plays a very important role (it can be used as reference for this video) [Highly recommended]
Here are a few ideas that you can use as topic. These were taken from the documentation guidelines as reference.

- [x] Current situation
- [x] Need
- [x] Ideas
- [x] Derrived Goals
- [x] Domain Description
- [x] Rough Sketches
- [x] Events, actions and behaviors
- [x] Requirements

Remember this script must be easy to read, highly informative and must capture the attention of the viewer.

**Comment by Jeimy-S** [comment]
script doc: https://docs.google.com/document/d/1qqPggS0pm14W4ARn0kl0qxlHnHwzlruzLYY-0qu_fuo/edit?usp=sharing
