### ISSUE TITLE
Write slides presenting the proposal

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#59]
Collaboration with the development team is needed for [Issue #58] in order to craft a comprehensive presentation outlining the script's purpose and content. The objective is to create a polished and visually appealing presentation suitable for the video proposal.

**Comment by Jeimy-S** [comment]
slides:  https://docs.google.com/presentation/d/1SDDZb4rVvmGV6H48nBXXcm41uroqNvPizdK7qS8tBZI/edit?usp=sharing
