### ISSUE TITLE
Record and Edit the Video proposal

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#60]
Recording and Presentation:

- We are in need of an individual with proficient presentation abilities who can confidently deliver our script. Strong communication skills are vital for this task.

Video Editing:

- After the recording, we require a skilled video editor who can craft a polished and professional video presentation.

YouTube Management:

- Prepare and upload the video to youtube and create a link that can be shared with the professor.

Collaboration with the development team for [Issue #58 ] is essential.

**Comment by Chosen-Juan1** [comment]
I could do the part regarding uploading the video to YouTube and giving the professor the link. Though, I must ask, isn’t it easier to hand over the video in a usb?

**Comment by AlfredoSoto1** [comment]
It has to be a link since that is what we are going to submit on moodle

**Comment by Chosen-Juan1** [comment]
Ok. When the video is available, the person could send it through here or to my email (juan.guadalupe@upr.edu), and I'll upload it.

**Comment by Chosen-Juan1** [comment]
If it's too big, i think google drive can be used to send large files.

**Comment by Chosen-Juan1** [comment]
I finished recording the video and handed it over for editing.

**Comment by JuanQ1226** [comment]
I edited and posted the video on moodle
