### ISSUE TITLE
Road Map Logic

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#66]
# Important
For this issue, you must follow [Issue #65] to understand the key features and design before implementation.

# Logic/Functionality in more detail

### Page Navigation Functionality:

- When you press any station it must redirect you to the workout screen.
- When the workout selection is selected, the screen must change to that screen.
- The map needs to be easy to navigate and present the stations.
- The design of the map should not be over filled with too many stations next to each other. It needs to be clear when you change from one station to another as your level progresses. 
- The stations are unlocked after the user passes a new level, this means that the future/high level stations must be locked
to the user until it reaches the desired level to unlock it.

### Display User Progress:

- The progress bar needs to present the progress in XP of the user that has collected so far.
- The level must be somwhere located in relation to the progressbar.

**Comment by AlfredoSoto1** [comment]
![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/108200951/a83765ef-5e36-4742-8978-65691d66f6bc)

**Comment by AlfredoSoto1** [comment]
This is an example diagram of how it should look/behave

**Comment by Chosen-Juan1** [comment]
This is a draft i have for the roadmap logic, i would like some ideas to further expand it (i would also like help in the areas where we have to load data so that it is displayed on screen).
[Roadmap psudocode.txt](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/files/12785546/Roadmap.psudocode.txt)

**Comment by Chosen-Juan1** [comment]
> This is an example diagram of how it should look/behave
Having a button (the one on the lower left) that leads from the roadmap to the roadmap is a bit redundant, Maybe it should lead to another page (like a settings or profile page).

**Comment by Alej24** [comment]
The image below shows the road map that I currently have. However, I'm not done working on it so I need a little more time to continue working on it.![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/99218281/e3c8b446-47d4-4d5f-99ce-02bfa9993591)

**Comment by JorgeC08** [comment]
A

> The image below shows the road map that I currently have. However, I'm not done working on it so I need a little more time to continue working on it.![image](https://user-images.githubusercontent.com/99218281/272734820-e3c8b446-47d4-4d5f-99ce-02bfa9993591.png)

Are you still working on it? Would you be able to push it to github to see it and expand on it? I've tried to make something similar but I need its base to it. I have some ideas in mind but I need the base to start from. Thanks!

**Comment by Alej24** [comment]
The text file below is from an app.js file I made separately.  I added locks to the locked stations, changed the colors, added diagonal lines between each station, and changed the icons of the bottom left and right buttons.

[Road map.txt](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/files/12850588/Road.map.txt)

**Comment by JuanQ1226** [comment]
Hello, any updates on implementing the roadmap ? If you need any technical help to do so or anything DM me.

**Comment by JuanQ1226** [comment]
I don't see a roadmap branch. if someone has an up to date one please publish it so that everyone can see what you guys are working on and give feedback and help.

**Comment by JorgeC08** [comment]
> I don't see a roadmap branch. if someone has an up to date one please publish it so that everyone can see what you guys are working on and give feedback and help.

I have a road map but was working on the the workout page. I can find it to work correctly so I'm currently seeing how to fix it so it shows right on the app. I could make a branch and uploaded. I changed the circles to rectangles since the front end told that it would be better that way

**Comment by Chosen-Juan1** [comment]
I'm currently working on queries so that the front end side of the app can retrieve information from the database.

**Comment by JuanQ1226** [comment]
@JorgeC08 Great! could you send me a screenshot or video of how the roadmap is working? Also upload the branch you are working on even if it is unfinished. **Unless you are working directly on the beta, which you really should not.**

**Comment by JuanQ1226** [comment]
@Chosen-Juan1 Ok how is it going?

**Comment by Chosen-Juan1** [comment]
I have enough understanding of SQL to write the needed queries, so I'm researching how to use these queries in python to ask for information from db (I believe its a library). Afterwards, I should be able to produce a working piece of code.

**Comment by JuanQ1226** [comment]
Great, tell me if you need anything else.

Juan Quintana
Computer Science and Engineering undergrad
***@***.***
1-(787)-403-0677
________________________________

**Comment by JuanQ1226** [comment]
Great, I've told @CristianMatos3 to help you in finishing the implementation.
