### ISSUE TITLE
Workout Creator Design

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#68]
# Description
The Workout Creator is the place where the user can create their custom Workouts.

# Ideal cases

- At the moment he can add up to 5 exercices per workout.

# Key Features

## Visuals/Display of workouts

- [ ] The user must see the custom workouts created.
- Workouts must be shown like a list.
- User can scroll down to see all of the workouts created.

## Workout creation

- [ ] The user can create a custom workout by selecting a set of already crafted exercises.
- [ ] There must be a button that the user can press that either opens a popup or redirects to a new screen.
- [ ] This new popup or screen needs to show to the user a list of exercises that he can select.
- Each exercise must show the icon image.
- It must display aswell the name of the exercise and a small description if you press a button with 
an icon (?) inside the exercise button.

## Workout customization after selection

- [ ] The order of the exercises after selection can be done.
- [ ] After the user selects the exercises, a new screen must be shown in which he can change the order of the exercises.
- [ ] After the user is happy with his selection and order of the exercises, he needs to be able to set the name of the workout.
- [ ] Set a custom description of the workout.
- [ ] Save the workout and then exit to the general workout screen where all the custom workouts are displayed.

## Edit workout after being created
 
- [ ] That custom workout needs a button that can redirect the user to edit the workout that he crafted.
- [ ] He can update the selection that he made.

**Comment by AlfredoSoto1** [comment]
![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/108200951/7a65dcd1-c3df-4d0f-a3cf-ee44917c4e2c)

**Comment by AlfredoSoto1** [comment]
This is a small diagram of how the flow should be

**Comment by RicardoGarciaSuarez** [comment]
<img width="320" alt="workout-unlocked" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/78510179/1fecdb5d-b3dc-4c4e-9012-9054fb479a9d">
<img width="303" alt="workout-locked" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/78510179/4ffd110b-323a-4486-a811-aa9349b3ea2f">
<img width="311" alt="create-the-way" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/78510179/84859513-5e49-4d9d-bcfb-6fe8959433f9">
<img width="297" alt="way-of-the-knight" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/78510179/4fd47c1b-4e57-43a6-a314-7f07729cc798">
<img width="326" alt="way-of-the-paladin" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/78510179/70c401fe-97ae-41cc-af09-31e1a801c22d">
<img width="311" alt="way-of-the-berserk" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/78510179/7d56215c-c0eb-46e2-b2e7-dc2477776511">
<img width="321" alt="way-of-the-dragonborn" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/78510179/e8407b32-463f-4a6a-a651-5e054219112b">


Here is the desing of the workout part of the application, starting with a preview of how the full unlocked workout screen will look one it has reach the necessary level to hay all the ways of fitness the app has to offer. The next preview is of the workout screen when you start without the full access of the ways yet it has the option for creating your exercises and the way of the knight referring to out beginners level. For the create a path preview it has to offer different types of exercises of arms, legs, back, abs and in those categories will be a list of exercises that works with the desired body part. The different ways previews have a similar desing with the difference being the intensity and difficulty of the exercises that they offer, delivering a more challenging workout.

**Comment by gabrielpadilla7** [comment]
Closing as the design is already finished. Old issue
