### ISSUE TITLE
Current workout in station

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#69]
# Description
The current workout station is the place where the user can track the progress, watch how the exercises are done and start the workout.

# Ideal cases

- A workout consists of 5 exercises maximum
- XP for each exercise is the same
- XP aditional earned from completing the workout must be between (1 ~ 2)XP points
- The maximum capacity of the progress bar must be 10 XP

# Key Features

## Visuals/Display

- [x] Progress must be displayed as a progress bar and the current level of the user.
- [ ] The workout to be done must be presented in a way that the user can see the exercises that is composed of.
- Each exercise displayed should contain an image representing the type of exercise.

- [ ] If the exercise is selected, information about the exercise should be displayed
- Name
- Description
- Small animation of 3 images (these images change every 1/2 seconds)
- XP of that exercise

## Start the workout

- [x] #81
- [x] When the workout gets finished, the user must earn the XP collected after completing the exercise
- [ ] After the workout is completed, the screen needs to go to **THIS** screen,
where the user can see the progress bar change and the workout
- [x] If the XP bar fills up completely, it must reset back to zero again and increase the level
- [x] Once the user level up, the next station must be unlocked in the Road Map. This means that there must be comunication from here to the team incharged of the Road Map feature when implementing this.

**Comment by JuanQ1226** [comment]
Any updates?

**Comment by JuanQ1226** [comment]
If someone has started a feature please telle because I'm going to be dividing this issue into smaller issues with only 2 people assigned.

**Comment by oscaroflores** [comment]
Queria ir haciendo un task para lo del progress bar y XP.

Estoy pensando crear un progress bar component que se conecta al xp del user e incrementa con cada finished workout. ¿Les suena como buena idea?

**Comment by CristianMatos3** [comment]
> Queria ir haciendo un task para lo del progress bar y XP.
> 
> 
> 
> Estoy pensando crear un progress bar component que se conecta al xp del user e incrementa con cada finished workout. ¿Les suena como buena idea?

Sounds good to me!

**Comment by oscaroflores** [comment]
Excelent, me voy a dejar llevar por eso. Algún voluntario que pueda trabajarlo conmigo?

**Comment by edgaelm** [comment]
@oscaroflores puedo trabajar contigo

**Comment by oscaroflores** [comment]
Ya te añadi @edgaelm

**Comment by oscaroflores** [comment]
Task has error...
" After the workout is completed, the screen needs to go to THIS screen,
where the user can see the progress bar change and the workout"

what screen??

**Comment by AlfredoSoto1** [comment]
Cuando seleccionen una estación dentro del roadmap, te tiene que llevar al workout station donde vas a ver el workout que se va a hacer. Lo que quiere decir esa parte del task es que cuando el usuario complete el workout, la pantalla tiene que regresar a el workout station que es basicamente la misma donde el vio el workout antes de empezarlo.

**Comment by LightPolution** [comment]
I implemented the tasks #2, #3, and #4 although it is not tested and is probably buggy (has not been pushed). I also tried to fix the bugs that were in the previous code

**Comment by oscaroflores** [comment]
> Cuando seleccionen una estación dentro del roadmap, te tiene que llevar al workout station donde vas a ver el workout que se va a hacer. Lo que quiere decir esa parte del task es que cuando el usuario complete el workout, la pantalla tiene que regresar a el workout station que es basicamente la misma donde el vio el workout antes de empezarlo.

Would it make more sense that it returns back to el roadmap page?
