### ISSUE TITLE
Create the timer -> Team 3 

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#7]
The timer is an essential feature for our program, it allows us to program sets of workouts and cooldowns

For this issue, we must create the timer. 

The following requirements are needed

- It should count down correctly
- The user should be able to input the number of minutes and seconds

#If any issues arise, please message your team leader or any of the managers
#Priority 10, Difficulty 3
#Good luck team!

**Comment by MarkoSchuetz** [comment]
> The user should be able to input the number of minutes and seconds

Are there any activities where durations that are better expressed in larger units? Hours, days,...?

**Comment by MarkoSchuetz** [comment]
> should

... does not make requirements.

**Comment by gabrielpadilla7** [comment]
> > The user should be able to input the number of minutes and seconds
> 
> Are there any activities where durations that are better expressed in larger units? Hours, days,...?

There are no activities that the user should be doing that needs to be expressed in larger units. Workout intervals last for minutes at a time, and cooldowns last either a few minutes or a few seconds.
