### ISSUE TITLE
Write a ReadMe with general information about the project

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#72]
# Description

Create a readme file that describes the essentials of this project

- [x] Project title
- [ ] Project's description
- [x] Table of contents
- [x] Installation
This is on how to setup the project on the machine, and how to include dependencies if necessary.

- [ ] Usage
Her you describe how to use the application with examples

- [ ] Configuration
If the project requires a configuration in relation to files, settings it must be explained here.

**Comment by oscaroflores** [comment]
@AlfredoSoto1 should I use the Readme on the project's root folder or inside the Front End folder?

**Comment by oscaroflores** [comment]
pequeño preview available en el branch.

**Comment by AlfredoSoto1** [comment]
You can create a branch that has your draft. Once its completed you can merge the branch to the beta. 
This readme can be on either one of these two:
- In the root folder, so that anyone who enters to the repo can see what the project is about and how to set it up.
- Have a new folder conveniently named "installation process" or "about software" where the readme can exist.

I prefer the one that is on the root folder since this should be the thing that anyone must read before going through the repo.
But you can choose to do which ever you feel is good for the project.

**Comment by oscaroflores** [comment]
Have been working on it, about 50% done

**Comment by AlfredoSoto1** [comment]
Algun update respecto al ReadMe?
