### ISSUE TITLE
Cooldown for the timer -> Team 3

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#9]
Cooldowns will allow users to take breaks in between intense workouts. 

For this issue, the following requirements must be met:

- After the timer has ended, it should start a cooldown mode automatically
- This cooldown mode could be set by the user, however a standard 30 second mode must be put if the user doesn't input anything for cooldown 

#If any issues arise, please message the team leader (if chosen) or managers
#Priority 8, Difficulty 2
#Good luck team!

**Comment by MarkoSchuetz** [comment]
If you can setup a sequence of exercise periods, then there is not really any need to treat the cool-down different to any other exercise.
