### ISSUE TITLE
List of changes to make:

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#93]
## List of changes to make:

- [x] Change the scope and span to include domain engineering, requirements engineering, software design, etc. and the span should go into more detail and be more specific.
- [x] The synopsis need to cover aspects of the whole project.
- [x] Adjust the domain talk about things in the domain that are relevant to the project in a way that’s independent of any implementation. We’re talking here about domain concepts and how they relate to one another and it should be clear that these concepts cannot only be entities, but also actions, events, and behaviors.
- [x] The other activities part shouldn’t be its own section but the content should be moved to existing areas where it’s relevant (In other word remove the other activities section and take the points mentioned to other sections).
- [x] Adjust the derived goals to be a little more “out of the way” but still easy to implement.
- [x] In the areas where we use diagrams we need to add text that gives context to those diagrams.
- [x] We need to add a legend to our “non-standard graphical language”
- [x] In the terminology we need to add operations that can be done with the entities mentioned, behaviors and events. Entities, actions (or functions), events, and behaviors must be in te same section not separate.
- [x] Change StopWatch to TimerTick
- [x] When you are describing domain behaviors then there can not be a user. Instead, we can talk about an exerciser starting, stopping, or resetting a timer, but not about a user interacting with any buttons.
- [x] Overlap between behaviors
- [x] The function signatures should not go into a section by themselves: their purpose is to complement the understanding of the domain actions and so they should be there with the description of the domain actions.”
- [x] Don’t write “as a user” in user stories, because it’s implied. Specify the type of user.
- [x] The player profile requirement should be split into parts and expanded.
- [x] Requirements must be measurable.
- [x] Traceability is not verification.

_Originally posted by @oscaroflores in https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/issues/71#issuecomment-1780277997_

**Comment by marcosarraiza** [comment]
Changed StopWatch to TimerTick and the overlap between behaviors

**Comment by AlfredoSoto1** [comment]
Necesito updates respecto al task que tienen asignado. Si completaron lo pedido, favor marcar el task como done y close el issue.

**Comment by YampierFernandez** [comment]
I checked some of the points on the list that were done but not marked. The missing points require me to read a little deeper but I will check them as soon as I can.

**Comment by YampierFernandez** [comment]
I have reviewed the missing points and I understand them to be addressed, so I will close the issue.
