### ISSUE TITLE
Documentation- Descriptive-Part(1)

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#98]
More deatails on each field in the Documentation Guidelines on moodle

This part of the documentation requires the following:

- [ ] 2.1 Domain Description
- [ ] 2.1.1 Domain rough sketch
- [ ] 2.1.2 Terminology
- [ ] 2.1.3 Domain terminology in relation to domain rough sketch

**Comment by AlfredoSoto1** [comment]
Aquí les dejo la rubrica como parte de lo que se debe mejorar en la documentación antes de añadir lo correspondiente.


![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/108200951/c13761f2-9191-4d2b-a8ab-32d307ee270e)

**Comment by AlfredoSoto1** [comment]
Recuerden que lo nuevo debe destacarse sobre lo que ya está puesto en la documentación

**Comment by edgaelm** [comment]
me puedes asignar esta tarea

**Comment by AlfredoSoto1** [comment]
Este issue está desactualizado ya que esta tarea está hecha. Te voy a asignar un task en relación al video presentación
